// This file is auto-generated by scripts/generate-indexes.mjs. Do not edit.

import automation0 from './example.event.trigger.js';
import automation1 from './example.email.trigger.js';

const allTriggers = [
    automation0,
    automation1,
];

export default allTriggers;
