// This file is auto-generated by scripts/generate-indexes.mjs. Do not edit.

import node0 from './text/string-uppercase.node.js';
import node1 from './text/analyze-sentiment.node.js';
import node2 from './utility/email-send.node.js';
import node3 from './utility/debug.node.js';
import node4 from './utility/database-query.node.js';
import node5 from './integration/webhook-trigger.node.js';
import node6 from './integration/webhook-response.node.js';
import node7 from './integration/http-request.node.js';
import node8 from './data/transform.node.js';
import node9 from './data/merge.node.js';
import node10 from './logic/loop-controller.node.js';
import node11 from './logic/delay.node.js';
import node12 from './logic/conditional.node.js';
import node13 from './utils/log/log-message.node.js';
import node14 from './ai/openai-completion.node.js';
import node15 from './ai/anthropic-claude.node.js';
import node16 from './ai/ai-response-parser.node.js';
import node17 from './google/gmail/listEmails.node.js';
import node18 from './google/gmail/connect.node.js';
import node19 from './google/gdrive/uploadFile.node.js';
import node20 from './google/gdrive/listFiles.node.js';
import node21 from './google/gdrive/downloadFile.node.js';

const allNodes = [
    node0,
    node1,
    node2,
    node3,
    node4,
    node5,
    node6,
    node7,
    node8,
    node9,
    node10,
    node11,
    node12,
    node13,
    node14,
    node15,
    node16,
    node17,
    node18,
    node19,
    node20,
    node21,
];

export default allNodes;
