// This file is auto-generated by scripts/generate-indexes.mjs. Do not edit.

import node0 from './text/string-uppercase.node.js';
import node1 from './text/analyze-sentiment.node.js';
import node2 from './utils/log/log-message.node.js';
import node3 from './google/gmail/listEmails.node.js';
import node4 from './google/gmail/connect.node.js';
import node5 from './google/gdrive/uploadFile.node.js';
import node6 from './google/gdrive/listFiles.node.js';
import node7 from './google/gdrive/downloadFile.node.js';

const allNodes = [
    node0,
    node1,
    node2,
    node3,
    node4,
    node5,
    node6,
    node7,
];

export default allNodes;
